# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1c7b26d980af7712115702e36f38614d51308495ef7daf477e8381b6665e371dda794bd8f6e257350b69b643772b07c81d0b39693229e9de50b5cbb55692c7b

test:
  secret_key_base: ccf8216dc3792e94419b7dd2485df2324ddeec1c27f7601f434bb216066b1c85409aedb8a2b6a4e2d20ffd067539f9c0fa8be2180f0b9c1ae0602840d2765a8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
